### PR TITLE
Update .blackfire.yml and remove scenario.bkf

### PR DESCRIPTION
**Pull request by ChristopheDujarric**
Since January 2019, scenarios run from the `.blackfire.yml` file fully supports the Blackfire Player DSL. https://blackfire.io/docs/cookbooks/scenarios

This pull request will enable all merchants/solution integrators to benefit from more actionable insights, getting closer to actual user behaviour on a site while generating profiles automatically.

The old `scenarios.bkf` file is no longer necessary.

### CODE REVIEW

**Comment by robbie-thompson** [comment]
@ChristopheDujarric The rule for scenario.bkf could also be removed in the .gitignore too: https://github.com/magento/magento-cloud/blob/ebbf7512721fc20739cb44a3f8577c8ede0f5c88/.gitignore#L23

**Comment by ChristopheDujarric** [comment]
> @ChristopheDujarric The rule for scenario.bkf could also be removed in the .gitignore too: https://github.com/ChristopheDujarric/magento-cloud/blob/a5f4dbe0227248a424e62ff22ccf6b105f1f8282/.gitignore#L23

Fixed! 👍

**Comment by ChristopheDujarric** [comment]
@billygilbert Is there anything I can do to help?

**Comment by billygilbert** [comment]
Since the scenarios in the previous `scenario.bkf` file do not work and moving them to the `.blackfire.yml` file cause the builds to begin failing, the best path forward is to close out this PR and make a separate one just simply removing the `scenarion.bkf` file as it no longer seems to be used.

We will put a separate task on the backlog to review the scenarios in the previous file / in this PR and look at fixing them.

**Pull request closed without merging**
