### PR TITLE
MAGETWO-91944: Transfer one of existing PAT scenarios to BlackFire

### PR DESCRIPTION
**Pull request by RuslanKostiv1**
* Added few scenarios and asserts to  .blackfire.yml
* Added scenarios for blackfire-player that reflect the most critical flows of Performance Acceptance Tests

### CODE REVIEW

**Comment by shiftedreality** [comment]
@RuslanKostiv1 are there gonna be more PRs to other branches?

**Comment by RuslanKostiv1** [comment]
@shiftedreality, at the moment PR to master is enough. PRs to other branches will be created in coming weeks.

**Comment by shiftedreality** [comment]
@RuslanKostiv1 please create a task and attach here. Also in our branching strategy, we're creating new branches from `master`. Next version `2.2.5` will contain these profiles. Is it accurate?

**Comment by RuslanKostiv1** [comment]
@shiftedreality , yes, correct.

**Pull request merged**
