### PR TITLE
MAGECLOUD-1180: Make ECE Template Cleaner

### PR DESCRIPTION
**Pull request by magearhiopterecs**
### Description
Base template for deployment Magento 2 on Magento Cloud.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by andriyShevtsov** [comment]
QA approved

**Comment by andriyShevtsov** [comment]
@NadiyaS  please approve it

**Comment by NadiyaS** [comment]
As I understand, with these configurations of composer.json, files from composer base will never be updated after the first installation. So, potentially, user will have outdated files (if they were updated from Magento side) and will never know about this until some error happens because of this outdation.

**Comment by andriyShevtsov** [comment]
QA approved

**Comment by magearhiopterecs** [comment]
@NadiyaS i returned property 'extra.magento-force:true' in back in composer.json. So when command 'composer update' or 'composer install' will be run then the package 'magento/magento-composer-installer' should update the skeleton of the project

**Pull request merged**
