### PR TITLE
increase default disk usage

### PR DESCRIPTION
**Pull request by r0fls**
This is resulting in a lot of MECE customers hitting their disk usage early on and raising critical support tickets. Is there a more sane default?

### CODE REVIEW

**Comment by r0fls** [comment]
cc @GuGuss

**Comment by ralt** [comment]
Unfortunately, the default allocated storage is 5GB. It's not reasonable to change the default disk usage to such a high one, as you don't want starting projects to fail.

If the plan's storage is increased to e.g. 50GB, the customer must be made aware that they need to increase it in their yaml files too.

**Comment by GuGuss** [comment]
Default is 50GB for MECE projects, so I guess this upgrade is fine.

**Comment by ralt** [comment]
If the default is 50GB, you might as well increase it for other services.

**Pull request closed without merging**
